### ISSUE TITLE
Error up running script

### ISSUE THREAD

**Issue by unseenmagik** [ClarkyKent/ingress_scraper#2]
```nitialize/Start DB Session
Connection clear
login with username password
Traceback (most recent call last):
  File "scrape_portal.py", line 177, in <module>
    IngressLogin = IntelMap(config['cookies'], config['username'], config['pwd'])
  File "/root/IngressScraperRDM/ingressAPI/ingress_api.py", line 84, in __init__
    self.login(cookie, username, password)
  File "/root/IngressScraperRDM/ingressAPI/ingress_api.py", line 98, in login
    login_url = re.findall('"(https://www\.google\.com/accounts/ServiceLogin.+?)"', _.text)[0]
IndexError: list index out of range```
```
Following the readme and adding all relevant data to the default.ini i get this error.
Any ideas ?

**Comment by TMHBOFH** [comment]
I have the same problem

**Comment by TMHBOFH** [comment]
@unseenmagik 
test please with this cookie text
![grafik](https://user-images.githubusercontent.com/12548049/68022800-a6d08e80-fca5-11e9-8f38-7403cf897849.png)

**Comment by unseenmagik** [comment]
@TMHBOFH did you manage to get it working ?
I copied that content as per the guide. I dodnt copy the `cookie:` part at the begining, just the content after the `:`

**Comment by ClarkyKent** [comment]
@unseenmagik  Something is wrong with your cookie part. Script try to connect via username/PWD if cookies fails and that part is not working since it has been changed, how you login.

So today only way to make it work is having valid cookie.

**Comment by TMHBOFH** [comment]
@unseenmagik 
yes it work for me

**Comment by Crippe83** [comment]
also check that you don't have any space in your password, that was the issue for me with the same error (IndexError)

**Comment by unseenmagik** [comment]
I am still unable to get this to work for me. 
i have followed the guide exactly how it should be done. 
See image of the cookie i am using in the default.ini

<img width="657" alt="image" src="https://user-images.githubusercontent.com/30931287/68806245-671e8500-065d-11ea-9c3e-a431bf6632be.png">

There is no space in my password. 

I even tried using the cookie from the Safair Developer tool also but that did not work either. 

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/30931287/68809985-02ffbf00-0665-11ea-8aac-c13504df1bb2.png">

**Comment by ClarkyKent** [comment]
@unseenmagik  Do you logout from intel?
I think you cookie becomes invalid if you logout.

**Comment by unseenmagik** [comment]
> @unseenmagik Do you logout from intel?
> I think you cookie becomes invalid if you logout.

I do not log out no.
I did log out. Log back in again and grab the new cookie but still would not run. 
It must be something really simple that im missing or doing but for the life of me i can not figure it out.

**Comment by unseenmagik** [comment]
IP banned on Server runs fine on local machine
